version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.0
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: npm-sane-reports-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
              sudo mkdir -p -m 777 $CIRCLE_ARTIFACTS
              sudo npm install npm@4 -g
              sudo npm install
      - save_cache:
          key: npm-sane-reports-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run production
      - run:
          name: Test
          command: |
              npm run lint
              npm run coverage
      - run:
          name: Create Artifact
          command:  tar -cvf sane-report.tar dist reportsServer.js
      - store_artifacts:
          path: sane-report.tar
          destination: sane-report
      - run:
          name: Deploy
          command: |
              mkdir sane-reports
              cp -avR dist sane-reports
              cp -avR templates sane-reports
              cp package.json sane-reports
              cp LICENSE sane-reports
              cp README.md sane-reports
              cp reportsServer.js sane-reports
              cd sane-reports
              sudo npm set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
              sudo npm publish sane-reports